# name: tushar
# on: push
# jobs:
#   test-job:
#     runs-on: ubuntu-latest
#     steps:
#      - name: Print message
#        run: echo "hello tushar"


name: tushar
on: push
jobs:
  test-job:
   runs-on: ubuntu-latest
   steps:
   - name: print message
     run: echo "hello tushar"
   - name: second image
     run: echo "hello pol"
   - name: third message
     run : echo "demo" 
  
