# name: tushar
# on: push
# jobs:
#   test-job:
#     runs-on: ubuntu-latest
#     steps:
#      - name: Print message
#        run: echo "hello tushar"


name: tushar
on: push
jobs:
  test-job:
   runs-on: ubuntu-latest
   steps:
     - name: print message
       run: echo "hello tushar"
  build-job:
   runs-on: ubuntu-latest
   steps:
     - name: buld  message
       run: echo "demo"
  deploy-job:
    runs-on: ubuntu-latest 
    steps:
     - name: deploy message
       run: echo "deploy-job"  

     
